context("common functions")

context("1. factorial_f")
test_that("factorial_f", {
  expect_equal(rfda:::factorial_f(0L), factorial(0))
  expect_equal(rfda:::factorial_f(1L), factorial(1))
  expect_equal(rfda:::factorial_f(2L), factorial(2))
  expect_equal(rfda:::factorial_f(3L), factorial(3))
  expect_equal(rfda:::factorial_f(5L), factorial(5))
  expect_true(is.nan(rfda:::factorial_f(-1)))
  expect_error(rfda:::factorial_f(0.5))
  expect_error(rfda:::factorial_f(2.5))
})

context("2. unique_rows")
M <- matrix(c(1,1,2,2,3,3,1,1,1,1,4,5), 6, 2)
resM <- matrix(c(1,2,3,3,1,1,4,5), 4, 2)
test_that("unique_rows", {
  expect_equal(unique_rows(M), resM)
  expect_error(unique_rows(rbind(M, c(1, NA))))
  expect_error(unique_rows(rbind(M, c(1, NaN))))
  expect_error(unique_rows(rbind(M, c(1, Inf))))
})

context("3. trapz")
xi <- 1:5
x <- c(1, 4, 9, 16, 25)
x2 <- matrix(c(1,4,9,16,25,1,8,27,64,125), 5)
test_that("trapz", {
  expect_equal(as.vector(trapz(x)), 42)
  expect_equal(as.vector(trapz(xi, x)), 42)
  expect_equal(as.vector(trapz(x2)), c(42, 162))
  expect_equal(as.vector(trapz(xi, x2)), c(42, 162))
  expect_error(trapz(c(NA, x)))
  expect_error(trapz(c(NaN, x)))
  expect_error(trapz(c(Inf, x)))
  expect_error(trapz(c(0, xi), x))
  expect_error(trapz(xi, c(0, x)))
  expect_error(trapz(c(1)))
  expect_error(trapz(c(0, xi), c(NA, x)))
  expect_error(trapz(c(0, xi), c(NaN, x)))
  expect_error(trapz(c(0, xi), c(Inf, x)))
  expect_error(trapz(c(NA, xi), c(0, x)))
  expect_error(trapz(c(NaN, xi), c(0, x)))
  expect_error(trapz(c(Inf, xi), c(0, x)))
})
