context("test - getFpcScores")

context("1. test - getFpcScoresIN validate input")
yMat <- matrix(rnorm(36), 6, 6) %>>% ((. + t(.)) / 2)
diag(yMat) <- diag(yMat) + 0.5
eigRes <- eigen(yMat)
splitVar <- rep(1, 6)
allTimePnts <- 1:6
meanFunc <- rnorm(6)
test_that("test - getFpcScoresIN validate input", {
  expect_error(rfda:::getFpcScoresIN(c(NA, allTimePnts[1:5]), splitVar, yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(c(NaN, allTimePnts[1:5]), splitVar, yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(c(Inf, allTimePnts[1:5]), splitVar, yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(c(1, allTimePnts), splitVar, yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, c(NA, splitVar[1:5]), yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, c(NaN, splitVar[1:5]), yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, c(Inf, splitVar[1:5]), yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, c(1, splitVar), yMat, eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, rbind(yMat[1:5, ], NA), eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, rbind(yMat[1:5, ], NaN), eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, rbind(yMat[1:5, ], Inf), eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, rbind(yMat, 1), eigRes$vectors, 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, rbind(eigRes$vectors[1:5, ], NA), 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, rbind(eigRes$vectors[1:5, ], NaN), 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, rbind(eigRes$vectors[1:5, ], Inf), 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, rbind(eigRes$vectors, 1), 0, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, NA, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, NaN, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, Inf, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, -1, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 2, eigRes$values, 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, c(NA, eigRes$values[1:5]), 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, c(NaN, eigRes$values[1:5]), 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, c(Inf, eigRes$values[1:5]), 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, c(1, eigRes$values), 2.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, 1:2))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, NA))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, NaN))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, Inf))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, -1.0))
  expect_error(rfda:::getFpcScoresIN(allTimePnts, splitVar, yMat, eigRes$vectors, 0, eigRes$values, 0.0))
})
