// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// factorial_f
double factorial_f(double k);
RcppExport SEXP rfda_factorial_f(SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    __result = Rcpp::wrap(factorial_f(k));
    return __result;
END_RCPP
}
// spline_f
arma::mat spline_f(const arma::vec& x, const arma::mat& y, const arma::vec& xi);
RcppExport SEXP rfda_spline_f(SEXP xSEXP, SEXP ySEXP, SEXP xiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xi(xiSEXP);
    __result = Rcpp::wrap(spline_f(x, y, xi));
    return __result;
END_RCPP
}
// interp1
arma::mat interp1(const arma::vec& x, const arma::mat& y, const arma::vec& xi, const std::string& method);
RcppExport SEXP rfda_interp1(SEXP xSEXP, SEXP ySEXP, SEXP xiSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    __result = Rcpp::wrap(interp1(x, y, xi, method));
    return __result;
END_RCPP
}
// interp2
arma::mat interp2(const arma::vec& x, const arma::vec& y, const arma::mat& v, const arma::vec& xi, arma::vec& yi, const std::string& method);
RcppExport SEXP rfda_interp2(SEXP xSEXP, SEXP ySEXP, SEXP vSEXP, SEXP xiSEXP, SEXP yiSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type yi(yiSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    __result = Rcpp::wrap(interp2(x, y, v, xi, yi, method));
    return __result;
END_RCPP
}
// locPoly1d
arma::vec locPoly1d(const double& bandwidth, const arma::vec& x, const arma::vec& y, const arma::vec& w, const arma::vec& xout, const std::string& kernel, const double& drv, const double& degree);
RcppExport SEXP rfda_locPoly1d(SEXP bandwidthSEXP, SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP xoutSEXP, SEXP kernelSEXP, SEXP drvSEXP, SEXP degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const double& >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type xout(xoutSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const double& >::type drv(drvSEXP);
    Rcpp::traits::input_parameter< const double& >::type degree(degreeSEXP);
    __result = Rcpp::wrap(locPoly1d(bandwidth, x, y, w, xout, kernel, drv, degree));
    return __result;
END_RCPP
}
// gcv_locPoly1d
double gcv_locPoly1d(arma::vec bwCand, const arma::vec& x, const arma::vec& y, const arma::vec& w, const std::string& kernel, const double& drv, const double& degree);
RcppExport SEXP rfda_gcv_locPoly1d(SEXP bwCandSEXP, SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP kernelSEXP, SEXP drvSEXP, SEXP degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type bwCand(bwCandSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< const double& >::type drv(drvSEXP);
    Rcpp::traits::input_parameter< const double& >::type degree(degreeSEXP);
    __result = Rcpp::wrap(gcv_locPoly1d(bwCand, x, y, w, kernel, drv, degree));
    return __result;
END_RCPP
}
// trapz_cpp
arma::mat trapz_cpp(const arma::vec& x, const arma::mat& y);
RcppExport SEXP rfda_trapz_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    __result = Rcpp::wrap(trapz_cpp(x, y));
    return __result;
END_RCPP
}
// unique_rows
arma::mat unique_rows(arma::mat x);
RcppExport SEXP rfda_unique_rows(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(unique_rows(x));
    return __result;
END_RCPP
}
