# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

factorial_f <- function(k) {
    .Call('rfda_factorial_f', PACKAGE = 'rfda', k)
}

quantileCpp <- function(x, probs) {
    .Call('rfda_quantileCpp', PACKAGE = 'rfda', x, probs)
}

spline_cpp <- function(x, y, xi) {
    .Call('rfda_spline_cpp', PACKAGE = 'rfda', x, y, xi)
}

interp1_cpp <- function(x, y, xi, method) {
    .Call('rfda_interp1_cpp', PACKAGE = 'rfda', x, y, xi, method)
}

#' 2-D data interpolation.
#'
#' Returns interpolated values of a 2-D function at specific query points using
#' linear interpolation. The extrapolation is used, please be caution in using the
#' values which xi is larger than max(x)/max(y) and smaller than min(x)/min(y).
#'
#' @param x A vector with n1 elements, x[i] is a support, i = 1, ..., n1.
#'   If x is not sorted, it will be sorted. If x is not unique, the corresponding V values
#'   will be averaged.
#' @param y A vector with n2 elements, y[j] is a support, j = 1, ..., n2.
#'   If y is not sorted, it will be sorted. If y is not unique, the corresponding V values
#'   will be averaged.
#' @param v A matrix with size n1 by n2, v[i, j] is the corresponding value at grid (x[i], y[j]).
#' @param xi A vector with m elements, xi[k] is the point which you want to interpolate,
#'   k = 1, ..., m1.
#' @param yi A vector with m elements, yi[l] is the point which you want to interpolate,
#'   l = 1, ..., m2.
#' @param method A string "linear" or "spline", the method of interpolation.
#' @return A matrix with the interpolated values corresponding to \code{xi} and \code{yi}.
#' @section Reference:
#' Cleve Moler, Numerical Computing with MATLAB, chapter 3,
#'   \url{http://www.mathworks.com/moler/index_ncm.html}. \cr
#' Kai Habel, Jaroslav Hajek, interp2, Octave.
#' @examples
#' # example in MatLab
#' library(lattice)
#' # data generation
#' x <- seq(-3, 3, 1)
#' xm <- expand.grid(x, x)
#' z <- 3*(1-xm[,1])^2.*exp(-(xm[,1]^2) - (xm[,2]+1)^2) -
#'   10*(xm[,1]/5 - xm[,1]^3 - xm[,2]^5)*exp(-xm[,1]^2-xm[,2]^2) -
#'   1/3*exp(-(xm[,1]+1)^2 - xm[,2]^2)
#' dat <- data.frame(xm, z)
#' # graph of original data
#' wireframe(z ~ Var1 + Var2, dat, drape = TRUE, colorkey = TRUE)
#'
#' xi <- seq(-3, 3, 0.25)
#' zi_l <- interp2(x, x, matrix(z, length(x)), xi, xi, 'linear')
#' dat_l <- data.frame(expand.grid(xi, xi), zi_l)
#' # graph of linearly interpolation
#' wireframe(zi_l ~ Var1 + Var2, dat_l, drape = TRUE, colorkey = TRUE)
#'
#' zi_s <- interp2(x, x, matrix(z, length(x)), xi, xi, 'spline')
#' dat_s <- data.frame(expand.grid(xi, xi), zi_s)
#' # graph of interpolation with spline
#' wireframe(zi_s ~ Var1 + Var2, dat_s, drape = TRUE, colorkey = TRUE)
#' @export
interp2 <- function(x, y, v, xi, yi, method) {
    .Call('rfda_interp2', PACKAGE = 'rfda', x, y, v, xi, yi, method)
}

#' One-dimensional kernel local polynominal smoother
#'
#' Perform one-dimensional kernel local polynominal smoother for data \code{(x,y)} with weight \code{w} on \code{xout}.
#'
#' @param bandwidth A single numerical value. The kernel smoothing parameter.
#' @param x A vector, the variable of of x-axis.
#' @param y A vector, the variable of of y-axis. \code{y[i]} is corresponding value of \code{x[i]}.
#' @param w A vector, the weight of data. \code{w[i]} is corresponding value of \code{x[i]}.
#' @param xout A vector, vector of output time points. It should be a sorted vecotr.
#' @param kernel A string. It could be 'gauss', 'gaussvar', 'epan' or 'quar'.
#' @param drv An integer, the order of derivative.
#' @param degree An integer, the degree of polynomial.
#' @return A estimated value on \code{xout} by one-dimensional kernel local polynominal smoother.
#' @examples
#' N <- 100
#' x <- runif(N, 0, 10)
#' y <- rnorm(N)
#' xout <- sort(runif(200, 0, 10))
#' est <- locPoly1d(1.2, x, y, rep(1, N), xout, 'gauss', 0, 1)
#' require(ggplot2)
#' ggplot(data.frame(x,y), aes(x,y)) + geom_point() +
#'   geom_line(aes(xout, est), data = data.frame(xout, est))
#' @export
locPoly1d <- function(bandwidth, x, y, w, xout, kernel, drv, degree) {
    .Call('rfda_locPoly1d', PACKAGE = 'rfda', bandwidth, x, y, w, xout, kernel, drv, degree)
}

#' Find the optimal bandwidth for one-dimensional kernel local polynominal smoother
#'
#' Find the optimal bandwidth used in \code{\link{locPoly1d}}.
#'
#' @param bwCand A numerical vector for the candidates of bandwidth
#' @param x A vector, the variable of of x-axis.
#' @param y A vector, the variable of of y-axis. \code{y[i]} is corresponding value of \code{x[i]}.
#' @param w A vector, the weight of data. \code{w[i]} is corresponding value of \code{x[i]}.
#' @param kernel A string. It could be 'gauss', 'gaussvar', 'epan' or 'quar'.
#' @param drv An integer, the order of derivative.
#' @param degree An integer, the degree of polynomial.
#' @return A optimal bandwidth selected by minimizing gcv scores.
#' @examples
#' data("regularExData", package = 'rfda')
#' regBwCand <- bwCandChooser(regularExData, "sampleID", "t", 2, "gauss", 1)
#' w <- rep(1, nrow(regularExData))
#' bw_opt <- gcvLocPoly1d(regBwCand, regularExData$t, regularExData$y, w, "gauss", 0, 1)
#' @export
gcvLocPoly1d <- function(bwCand, x, y, w, kernel, drv, degree) {
    .Call('rfda_gcvLocPoly1d', PACKAGE = 'rfda', bwCand, x, y, w, kernel, drv, degree)
}

#' One-dimensional kernel local polynominal smoother of quantiles
#'
#' Perform one-dimensional kernel local polynominal smoother of quantiles corresponding to the
#' given probabilities for data \code{(x,y)} with weight \code{w} on \code{xout}.
#'
#' @param bandwidth A single numerical value. The kernel smoothing parameter.
#' @param probs A numeric vector with values between 0 and 1. The probabilities of quantiles.
#' @param x A vector, the variable of of x-axis.
#' @param y A vector, the variable of of y-axis. \code{y[i]} is corresponding value of \code{x[i]}.
#' @param w A vector, the weight of data. \code{w[i]} is corresponding value of \code{x[i]}.
#' @param xout A vector, vector of output time points. It should be a sorted vecotr.
#' @param kernel A string. It could be 'gauss', 'gaussvar', 'epan' or 'quar'.
#' @param drv An integer, the order of derivative.
#' @param degree An integer, the degree of polynomial.
#' @return A estimated value on \code{xout} by one-dimensional kernel local polynominal smoother of quantiles
#' corresponding to the given probabilities.
#' @references
#' \enumerate{
#'   \item https://www.r-statistics.com/2010/04/quantile-loess-combining-a-moving-quantile-window-with-loess-r-function
#' }
#' @examples
#' N <- 100
#' x <- runif(N, 0, 10)
#' y <- rnorm(N)
#' xout <- sort(runif(200, 0, 10))
#' est <- locPoly1d(1.2, x, y, rep(1, N), xout, 'gauss', 0, 1)
#' require(pipeR)
#' require(data.table)
#' est_quant <- locQuantPoly1d(1.2, c(0.25, 0.5, 0.75), x, y, rep(1, N), xout, 'gauss', 0, 1) %>>%
#'   data.table %>>% setnames(c("Q25", "Q50", "Q75"))
#' linesDF <- est_quant[ , `:=`(x = xout, loess = est)] %>>% melt.data.table("x", value.name = "y")
#' require(ggplot2)
#' ggplot(data.frame(x,y), aes(x, y)) + geom_point() +
#'   geom_line(aes(x, y, colour = variable), data = linesDF) +
#'   labs(colour = "Type")
#' @export
locQuantPoly1d <- function(bandwidth, probs, x, y, w, xout, kernel, drv, degree) {
    .Call('rfda_locQuantPoly1d', PACKAGE = 'rfda', bandwidth, probs, x, y, w, xout, kernel, drv, degree)
}

trapz_cpp <- function(x, y) {
    .Call('rfda_trapz_cpp', PACKAGE = 'rfda', x, y)
}

#' unique rows
#'
#' Return the unique rows with quick sort algorithm.
#'
#' @param x A matrix.
#' @return A matrix with unique rows.
#' @examples
#' unique_rows(matrix(c(1,1,2,2,3,3,1,1,1,1,4,5),, 2))
#' #      [,1] [,2]
#' # [,1]    1    1
#' # [,2]    2    1
#' # [,3]    3    4
#' # [,4]    3    5
#' @export
unique_rows <- function(x) {
    .Call('rfda_unique_rows', PACKAGE = 'rfda', x)
}

